#!/usr/bin/env python3

"""Generate the build.ninja file for waves."""

import argparse
import os
import platform
import sys

from vendor.ninja import ninja_syntax

parser = argparse.ArgumentParser(description="Configure the waves build.")
parser.add_argument("--debug", action="store_true", help="enable debug flags")
parser.add_argument(
    "--gbdk-home",
    default="tools/gbdk/",
    help="path to GBDK installation (default: tools/gbdk/)",
)

args = parser.parse_args()

BUILD_FILENAME = "build.ninja"
buildfile = open(BUILD_FILENAME, "w")
n = ninja_syntax.Writer(buildfile)

n.comment("This file is generated by configure.py -- do not edit.")
n.comment("To regenerate: python3 configure.py")
n.newline()

# Regenerate build.ninja when configure.py or ninja_syntax.py changes.
n.variable("configure_args", " ".join(sys.argv[1:]))
n.rule(
    "configure",
    command="${python} configure.py ${configure_args}",
    generator=True,
    description="configure ${configure_args}",
)
n.build(
    "build.ninja",
    "configure",
    implicit=["configure.py", "vendor/ninja/ninja_syntax.py"],
)
n.newline()

n.variable("python", sys.executable)
n.variable("builddir", "build")
n.newline()

# --- ROM toolchain ---

gbdk_home = args.gbdk_home
if not gbdk_home.endswith("/"):
    gbdk_home += "/"

n.variable("gbdk_home", gbdk_home)
n.variable("cc", "${gbdk_home}bin/lcc")
n.variable("romusage", "${gbdk_home}bin/romusage")

cflags = ["-Wa-l", "-Wl-m", "-Wl-j", "-msm83:gb", "-Isrc/waves", "-Isrc/midilink"]
if args.debug:
    cflags += ["-debug", "-v"]
n.variable("cflags", cflags)
n.newline()

n.rule("cc_gb", command="$cc $cflags -c -o $out $in", description="CC $out")
n.newline()

n.rule(
    "link_gb",
    command="$cc $cflags -o $out $in && $romusage $mapfile",
    description="LINK $out",
)
n.newline()

# --- ROM build edges ---

game = "waves"

n.build(
    "$builddir/waves.o",
    "cc_gb",
    "src/waves/waves.c",
    implicit=["src/waves/waves.h", "src/waves/envelope.h", "src/midilink/protocol.h"],
)
n.build(
    "$builddir/envelope.o",
    "cc_gb",
    "src/waves/envelope.c",
    implicit=["src/waves/envelope.h"],
)
n.newline()

n.build(
    "$builddir/" + game + ".gb",
    "link_gb",
    ["$builddir/waves.o", "$builddir/envelope.o"],
    variables={"mapfile": "$builddir/" + game + ".map"},
)
n.newline()

n.default("$builddir/" + game + ".gb")
n.newline()

# --- SameBoy ---

sameboy_root = "vendor/SameBoy"
sameboy_lib = os.path.join(sameboy_root, "build", "lib", "libsameboy.a")

n.variable("host_cc", "gcc")
n.newline()

# SameBoy is built by its own Makefile; treat it as an external dependency.
tools_dir = os.path.abspath("tools")
n.rule(
    "sameboy",
    command='PATH="'
    + tools_dir
    + ':$$PATH" make -C '
    + sameboy_root
    + " headers lib CONF=release EXTRA_CFLAGS=-fPIC",
    description="MAKE SameBoy",
    generator=True,
)
n.build(sameboy_lib, "sameboy")
n.newline()

# Shared library for Python ctypes bindings.
if platform.system() == "Darwin":
    shlib_ext = ".dylib"
    whole_archive = "-Wl,-all_load"
    no_whole_archive = ""
else:
    shlib_ext = ".so"
    whole_archive = "-Wl,--whole-archive"
    no_whole_archive = "-Wl,--no-whole-archive"

sameboy_so = os.path.join("$builddir", "lib", "libsameboy" + shlib_ext)
n.rule(
    "shlib",
    command="$host_cc -shared -o $out "
    + whole_archive
    + " $in "
    + no_whole_archive
    + " -lm",
    description="SHLIB $out",
)
n.build(sameboy_so, "shlib", [sameboy_lib])
n.newline()

n.close()
print("wrote %s." % BUILD_FILENAME)
