#!/usr/bin/env python3

"""Generate the build.ninja file for waves."""

import argparse
import glob
import os
import platform
import re
import sys

from vendor.ninja import ninja_syntax

parser = argparse.ArgumentParser(description="Configure the waves build.")
parser.add_argument("--debug", action="store_true", help="enable debug flags")
parser.add_argument(
    "--gbdk-home",
    default="tools/gbdk/",
    help="path to GBDK installation (default: tools/gbdk/)",
)

args = parser.parse_args()

BUILD_FILENAME = "build.ninja"
buildfile = open(BUILD_FILENAME, "w")
n = ninja_syntax.Writer(buildfile)

n.comment("This file is generated by configure.py -- do not edit.")
n.comment("To regenerate: python3 configure.py")
n.newline()

# Regenerate build.ninja when configure.py or ninja_syntax.py changes.
n.variable("configure_args", " ".join(sys.argv[1:]))
n.rule(
    "configure",
    command="${python} configure.py ${configure_args}",
    generator=True,
    description="configure ${configure_args}",
)
n.build(
    "build.ninja",
    "configure",
    implicit=["configure.py", "vendor/ninja/ninja_syntax.py"],
)
n.newline()

n.variable("python", sys.executable)
n.variable("builddir", "build")
n.newline()

# --- ROM toolchain ---

gbdk_home = args.gbdk_home
if not gbdk_home.endswith("/"):
    gbdk_home += "/"

n.variable("gbdk_home", gbdk_home)
n.variable("cc", "${gbdk_home}bin/lcc")
n.variable("romusage", "${gbdk_home}bin/romusage")

cflags = ["-Wa-l", "-Wl-m", "-Wl-j", "-msm83:gb", "-Isrc/waves", "-Isrc/midilink"]
if args.debug:
    cflags += ["-debug", "-v"]
n.variable("cflags", cflags)
n.newline()

n.rule("cc_gb", command="$cc $cflags -c -o $out $in", description="CC $out")
n.newline()

n.rule(
    "link_gb",
    command="$cc $cflags -o $out $in && $romusage $mapfile",
    description="LINK $out",
)
n.newline()

# --- ROM build edges ---

game = "waves"

n.build(
    "$builddir/waves.o",
    "cc_gb",
    "src/waves/waves.c",
    implicit=["src/waves/waves.h", "src/waves/envelope.h", "src/midilink/protocol.h"],
)
n.build(
    "$builddir/envelope.o",
    "cc_gb",
    "src/waves/envelope.c",
    implicit=["src/waves/envelope.h"],
)
n.newline()

n.build(
    "$builddir/" + game + ".gb",
    "link_gb",
    ["$builddir/waves.o", "$builddir/envelope.o"],
    variables={"mapfile": "$builddir/" + game + ".map"},
)
n.newline()

n.default("$builddir/" + game + ".gb")
n.newline()

# --- SameBoy ---

sameboy_root = "vendor/sameboy"

# Read version from vendored version.mk.
with open(os.path.join(sameboy_root, "version.mk")) as f:
    sameboy_version = re.search(r"VERSION\s*:=\s*(.+)", f.read()).group(1).strip()

# Extract copyright year from the LICENSE file.
with open(os.path.join(sameboy_root, "LICENSE")) as f:
    sameboy_copyright_year = re.search(r"(20[2-9]\d)", f.read()).group(1)

n.variable("host_cc", "cc")
n.newline()

# Compile SameBoy Core sources directly.
sameboy_cflags = [
    "-std=gnu11",
    "-D_GNU_SOURCE",
    "-DGB_INTERNAL",
    f'-DGB_VERSION=\'"{sameboy_version}"\'',
    f'-DGB_COPYRIGHT_YEAR=\'"{sameboy_copyright_year}"\'',
    "-D_USE_MATH_DEFINES",
    f"-I{sameboy_root}",
    "-fPIC",
    "-O3",
    "-ffast-math",
    "-DNDEBUG",
    "-Wall",
    "-Wno-multichar",
    "-Wno-unknown-warning-option",
]

n.variable("sameboy_cflags", " ".join(sameboy_cflags))
n.newline()

n.rule(
    "cc_sameboy",
    command="$host_cc $sameboy_cflags -MMD -MF $out.d -c -o $out $in",
    depfile="$out.d",
    description="CC $out",
)
n.newline()

core_sources = sorted(glob.glob(os.path.join(sameboy_root, "Core", "*.c")))
core_objects = []
for src in core_sources:
    obj = os.path.join("$builddir", "sameboy", os.path.basename(src) + ".o")
    n.build(obj, "cc_sameboy", src)
    core_objects.append(obj)
n.newline()

sameboy_lib = os.path.join("$builddir", "lib", "libsameboy.a")
n.rule("ar", command="rm -f $out && ar crs $out $in", description="AR $out")
n.build(sameboy_lib, "ar", core_objects)
n.newline()

# Shared library for Python ctypes bindings.
if platform.system() == "Darwin":
    shlib_ext = ".dylib"
    whole_archive = "-Wl,-all_load"
    no_whole_archive = ""
else:
    shlib_ext = ".so"
    whole_archive = "-Wl,--whole-archive"
    no_whole_archive = "-Wl,--no-whole-archive"

sameboy_so = os.path.join("$builddir", "lib", "libsameboy" + shlib_ext)
n.rule(
    "shlib",
    command="$host_cc -shared -o $out "
    + whole_archive
    + " $in "
    + no_whole_archive
    + " -lm",
    description="SHLIB $out",
)
n.build(sameboy_so, "shlib", [sameboy_lib])
n.newline()

n.close()
print("wrote %s." % BUILD_FILENAME)
